# Generated by Django 3.1.7 on 2021-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210325_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='currentcountry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='origincountry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationshipstatus',
            field=models.CharField(blank=True, choices=[('s', 'single'), ('m', 'married'), ('w', 'widowed'), ('r', 'in a relationship')], max_length=50),
        ),
    ]
