# Generated by Django 3.1.7 on 2021-04-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210411_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currentcountry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='origincountry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationshipstatus',
            field=models.CharField(blank=True, choices=[('s', 'single'), ('m', 'married'), ('w', 'widowed'), ('r', 'in a relationship')], max_length=50, null=True),
        ),
    ]
