# Generated by Django 3.1.7 on 2021-04-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='_answer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='_comment',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='_question',
        ),
    ]
