# Generated by Django 3.1.7 on 2021-04-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210422_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='upVotes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
