# Generated by Django 3.1.7 on 2021-04-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210423_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='whichAnswer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allComments', to='home.answer'),
        ),
    ]
